stages:
  - build
  
build:
  stage: build
  script:
    - c:\cygwin64\bin\bash c:\Projects\mdanse\resources\package.sh setup
    - c:\cygwin64\bin\bash c:\Projects\mdanse\resources\package.sh build
    - c:\cygwin64\bin\bash c:\Projects\mdanse\resources\upload.sh
  only:
    - master
  tags:
    - windows