stages:
  - build

osx:
  stage: build
  script:
    - cd ./BuildServer/Darwin/Scripts
    - ./package.sh
  tags:
    - mac
  only:
    - tags
  allow_failure: false
  artifacts:
    paths:
    - BuildServer/Darwin/Build/*.dmg
  
windows:
  stage: build
  script:
    - c:\cygwin64\bin\bash -c "dos2unix.exe ./BuildServer/Windows/package.sh"
    - c:\cygwin64\bin\bash .\BuildServer\Windows\package.sh setup
    - c:\cygwin64\bin\bash .\BuildServer\Windows\package.sh build
  only:
    - tags
  tags:
    - windows
  allow_failure: false
