stages:
  - ci
  - deploy
 
# trusty pipeline
ci:trusty:
  stage: ci
  script:
    - ./BuildServer/Debian/run_build.sh
    - ./BuildServer/Debian/run_tests.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - release
    - hotfix
    - develop
    - /^feature-.*$/
    - /^bugfix-.*$/
  artifacts:
    paths:
    - build
    expire_in: 1 day
  tags:
    - ubuntu16.04

deploy:trusty:
  stage: deploy
  script:
    - ./BuildServer/Debian/run_deploy.sh amd64 trusty
  only:
    - tags
    - develop
  dependencies:
    - ci:trusty
  when: on_success
  artifacts:
    paths:
    - ./BuildServer/Debian/Build/*.deb
  tags:
    - ubuntu16.04

# osx pipeline
ci:osx:
  stage: ci
  script:
    - ./BuildServer/Darwin/Scripts/run_build.sh
    - ./BuildServer/Darwin/Scripts/run_tests.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - release
    - hotfix
    - develop
    - /^feature-.*$/
    - /^bugfix-.*$/
  artifacts:
    paths:
    - build
    expire_in: 1 day
  tags:
    - macos10.13

test:osx:
  stage: test
  script:
    - ./BuildServer/Darwin/Scripts/run_tests.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - release
    - hotfix
    - develop
    - /^feature-.*$/
    - /^bugfix-.*$/
  dependencies:
    - build:osx
  tags:
    - macos10.13

deploy:osx:
  stage: deploy
  script:
    - ./BuildServer/Darwin/Scripts/run_deploy.sh
  only:
    - tags
    - develop
  dependencies:
    - ci:osx
  when: on_success
  artifacts:
    paths:
     - BuildServer/Darwin/Build/*.dmg
  tags:
    - macos10.13

# windows 7 pipeline
ci:windows:
  stage: ci
  script:
    - .\BuildServer\\Windows\\run_build.bat
    - .\BuildServer\\Windows\\run_tests.bat
  allow_failure: false
  only:
    - triggers
    - tags
    - develop
    - release
    - hotfix
    - /^feature-.*$/
    - /^bugfix-.*$/
  artifacts:
    paths:
    - .\BuildServer\Windows\Build
    expire_in: 1 day
  dependencies:
    - build:windows
  tags:
    - windows

deploy:windows:
  stage: deploy
  script:
    - .\BuildServer\\Windows\\run_deploy.bat
  only:
    - tags
    - develop
  dependencies:
    - ci:windows
  when: on_success
  artifacts:
    paths:
     - BuildServer/Windows/Build/MDANSE*.exe
  tags:
    - windows

