linux:
  script:
    - ./BuildServer/Debian/build_deb.sh amd64 trusty
  only:
    - master 
  tags:
    - ubuntu14.04
    
windows:
  script:
#    - c:\cygwin64\bin\bash c:\Projects\mdanse\resources\package.sh setup
#    - c:\cygwin64\bin\bash c:\Projects\mdanse\resources\package.sh build
    - c:\Projects\mdanse\resources\upload.bat
  only:
    - master
  tags:
    - windows