stages:
  - ci
  - deploy
  - clean

# xenial pipeline
ci:xenial:
  stage: ci
  script:
    - source ./BuildServer/Unix/definitions_debian.sh
    - source ./BuildServer/Unix/version.sh
    - ./BuildServer/Unix/clean.sh
    - ./BuildServer/Unix/build.sh
    - ./BuildServer/Unix/tests.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - release
    - hotfix
    - develop
    - /^feature-.*$/
    - /^bugfix-.*$/
  artifacts:
    paths:
    - ./BuildServer/Unix/Build
    expire_in: 1 day
  tags:
    - ubuntu16.04
deploy:xenial:
  stage: deploy
  script:
    - ./BuildServer/Unix/deploy_debian.sh
  only:
    - tags
    - develop
  dependencies:
    - ci:xenial
  when: on_success
  artifacts:
    paths:
     - BuildServer/MDANSE*.deb
  tags:
    - ubuntu16.04
clean:xenial:
  stage: clean
  script:
    - ./BuildServer/Unix/clean.sh
  tags:
    - ubuntu16.04

# osx pipeline
ci:osx:
  stage: ci
  script:
    - source ./BuildServer/Unix/definitions_macos.sh
    - source ./BuildServer/Unix/version.sh
    - ./BuildServer/Unix/clean.sh
    - ./BuildServer/Unix/build.sh
    - ./BuildServer/Unix/tests.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - release
    - hotfix
    - develop
    - /^feature-.*$/
    - /^bugfix-.*$/
  artifacts:
    paths:
    - ./BuildServer/Unix/Build
    expire_in: 1 day
  tags:
    - macos10.13
deploy:osx:
  stage: deploy
  script:
    - ./BuildServer/Unix/deploy_macos.sh
  only:
    - tags
    - develop
  dependencies:
    - ci:osx
  when: on_success
  artifacts:
    paths:
     - BuildServer/MDANSE*.dmg
  tags:
    - macos10.13
clean:osx:
  stage: clean
  script:
    - ./BuildServer/Unix/clean.sh
  tags:
    - macos10.13

# windows 7 pipeline
# "call" is mandatory, see https://gitlab.com/gitlab-org/gitlab-runner/issues/1051
ci:windows:
  stage: ci
  script:
    - call .\\BuildServer\\Windows\\definitions.bat
    - call .\\BuildServer\\Windows\\version.bat
    - call .\\BuildServer\\Windows\\clean.bat
    - call .\\BuildServer\\Windows\\build.bat
    - call .\\BuildServer\\Windows\\tests.bat
  allow_failure: false
  only:
    - triggers
    - tags
    - develop
    - release
    - hotfix
    - /^feature-.*$/
    - /^bugfix-.*$/
  artifacts:
    paths:
    - .\\BuildServer\\Windows\\Build
    expire_in: 1 day
  tags:
    - windows10
deploy:windows:
  stage: deploy
  script:
    - call .\\BuildServer\\Windows\\deploy.bat
  only:
    - tags
    - develop
  dependencies:
    - ci:windows
  when: on_success
  artifacts:
    paths:
     - BuildServer\\MDANSE*.exe
  tags:
    - windows10
clean:windows:
  stage: clean
  script:
    - call .\\BuildServer\\Windows\\clean.bat
  tags:
    - windows10
