windows:
  script:
    - c:\cygwin64\bin\bash .\BuildServer\WIndows\package.sh setup
    - c:\cygwin64\bin\bash .\BuildServer\WIndows\package.sh build
  only:
    - master
  tags:
    - windows

#linux:
#  script:
#    - ./BuildServer/Debian/build_deb.sh amd64 trusty
#  only:
#    - master 
#  tags:
#    - ubuntu14.04

#mac:
#  script:
#    - cd ./BuildServer/Darwin/Scripts
#    - ./package.sh
#  only:
#    - master
#  tags:
#    - mac