windows:
  script:
    - c:\cygwin64\bin\bash c:\Projects\mdanse\resources\package.sh setup
    - c:\cygwin64\bin\bash c:\Projects\mdanse\resources\package.sh build
    - cmd /C c:\Projects\mdanse\resources\upload.bat
  only:
    - master
  tags:
    - windows

linux:
  script:
    - ./BuildServer/Debian/build_deb.sh amd64 trusty
  only:
    - master 
  tags:
    - ubuntu14.04

macos:
  script:
    - cd ./BuildServer/Darwin/Scripts
    - ./package.sh
  only:
    - master
  tags:
    - mac