stages:
  - build
  - test
  - deploy
 
# trusty pipeline
build:trusty:
  stage: build
  script:
    - ./BuildServer/Debian/run_build.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - /^feature-.*$/
    - /^release-.*$/
    - /^hotfix-.*$/
    - /^bugfix-.*$/
    - develop
  artifacts:
    paths:
    - build
    expire_in: 1 day
  tags:
    - ubuntu14.04

test:trusty:
  stage: test
  script:
    - ./BuildServer/Debian/run_tests.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - /^feature-.*$/
    - /^release-.*$/
    - /^hotfix-.*$/
    - /^bugfix-.*$/
    - develop
  dependencies:
    - build:trusty
  tags:
    - ubuntu14.04

deploy:trusty:
  stage: deploy
  script:
    - ./BuildServer/Debian/run_deploy.sh amd64 trusty
  only:
    - triggers
    - tags
    - develop
  when: on_success
  artifacts:
    paths:
    - ./BuildServer/Debian/Build/*.deb
  tags:
    - ubuntu14.04

# osx pipeline

build:osx:
  stage: build
  script:
    - ./BuildServer/Darwin/Scripts/run_build.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - /^feature-.*$/
    - /^release-.*$/
    - /^hotfix-.*$/
    - /^bugfix-.*$/
    - develop
  artifacts:
    paths:
    - build
    expire_in: 1 day
  tags:
    - ci-macmini2

test:osx:
  stage: test
  script:
    - ./BuildServer/Darwin/Scripts/run_tests.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - /^feature-.*$/
    - /^release-.*$/
    - /^hotfix-.*$/
    - /^bugfix-.*$/
    - develop
  dependencies:
    - build:osx
  tags:
    - ci-macmini2

deploy:osx:
  stage: deploy
  script:
    - ./BuildServer/Darwin/Scripts/run_deploy.sh
  only:
    - triggers
    - tags
    - develop
  when: on_success
  artifacts:
    paths:
     - BuildServer/Darwin/Build/*.dmg
  tags:
    - ci-macmini2

# # windows 7 pipeline

build:windows:
  stage: build
  script:
    - c:\cygwin64\bin\bash -c "dos2unix.exe ./BuildServer/Windows/run_build.sh"
    - c:\cygwin64\bin\bash -c "chmod a+x ./BuildServer/Windows/run_build.sh"
    - c:\cygwin64\bin\bash -c "./BuildServer/Windows/run_build.sh"
  allow_failure: false
  only:
    - triggers
    - tags
    - /^feature-.*$/
    - /^release-.*$/
    - /^hotfix-.*$/
    - /^bugfix-.*$/
    - develop
  artifacts:
    paths:
    - .\BuildServer\Windows\Build
    expire_in: 1 day
  tags:
    - windows

test:windows:
  stage: test
  script:
    - c:\cygwin64\bin\bash -c "dos2unix.exe ./BuildServer/Windows/run_tests.sh"
    - c:\cygwin64\bin\bash -c "chmod a+x ./BuildServer/Windows/run_tests.sh"
    - c:\cygwin64\bin\bash -c "./BuildServer/Windows/run_tests.sh"
  allow_failure: false
  only:
    - triggers
    - tags
    - /^feature-.*$/
    - /^release-.*$/
    - /^hotfix-.*$/
    - /^bugfix-.*$/
    - develop
  dependencies:
    - build:windows
  tags:
    - windows

deploy:windows:
  stage: deploy
  script:
    - c:\cygwin64\bin\bash -c "dos2unix.exe ./BuildServer/Windows/run_deploy.sh"
    - c:\cygwin64\bin\bash -c "chmod a+x ./BuildServer/Windows/run_deploy.sh"
    - c:\cygwin64\bin\bash -c "./BuildServer/Windows/run_deploy.sh"
  only:
    - triggers
    - tags
    - develop
  when: on_success
  artifacts:
    paths:
     - BuildServer/Windows/Build/MDANSE*.exe
  tags:
    - windows

