stages:
  - build
  - test
  - deploy

# trusty pipeline

build:trusty:
  stage: build
  script:
    - ./BuildServer/Debian/run_build.sh
  only:
    - tags
  allow_failure: false
  tags:
    - ubuntu14.04

test:trusty:
  stage: test
  script:
    - ./BuildServer/Debian/run_tests.sh
  allow_failure: false
  tags:
    - ubuntu14.04

deploy:trusty:
  stage: deploy
  script:
    - ./BuildServer/Debian/run_deploy.sh amd64 trusty
  only:
    - tags
  when: on_success
  artifacts:
    paths:
    - ./BuildServer/Debian/Build/*.deb
  tags:
    - ubuntu14.04

# osx pipeline

build:osx:
  stage: build
  script:
    - cd ./BuildServer/Darwin/Scripts
    - ./run_build.sh
  allow_failure: false
  tags:
    - mac

test:osx:
  stage: test
  script:
    - cd ./BuildServer/Darwin/Scripts
    - ./run_tests.sh
  allow_failure: false
  tags:
    - mac

deploy:osx:
  stage: deploy
  script:
    - cd ./BuildServer/Darwin/Scripts
    - ./run_deploy.sh
  only:
    - tags
  when: on_success
  artifacts:
    paths:
      - BuildServer/Darwin/Build/*.dmg
  tags:
    - mac

#windows:
#  stage: build
#  script:
#    - c:\cygwin64\bin\bash -c "dos2unix.exe ./BuildServer/Windows/package.sh"
#    - c:\cygwin64\bin\bash .\BuildServer\Windows\package.sh setup
#    - c:\cygwin64\bin\bash .\BuildServer\Windows\package.sh build
#  artifacts:
#    paths:
#    - BuildServer/Windows/Build/MDANSE*.exe
#  only:
#    - tags
#    - triggers
#  tags:
#    - windows
#  allow_failure: false
