stages:
  - ci
  - deploy

# ubuntu pipeline
ci:ubuntu_xenial:
  stage: ci
  script:
    - docker build --force-rm --build-arg MDANSE_GIT_COMMIT=${CI_COMMIT_SHA} -t ci_mdanse_xenial -f ./BuildServer/Docker/Builder/Dockerfile_build .
  allow_failure: false
  only:
    - triggers
    - tags
    - release
    - hotfix
    - develop
    - /^feature-.*$/
    - /^bugfix-.*$/
  tags:
    - docker
    - sci
    - ubuntu

# ubuntu pipeline
deploy:ubuntu_xenial:
  stage: deploy
  script:
    - docker build --force-rm -t deploy_mdanse_xenial -f ./BuildServer/Docker/Builder/Dockerfile_deploy .
    - chmod 755 ./BuildServer/Docker/upload_artefacts.sh
    - echo `pwd`
    - ./BuildServer/Docker/upload_artefacts.sh
    - echo `ls`
    - echo `pwd`
    - echo ${CI_PROJECT_DIR}
  allow_failure: false
  only:
    - triggers
    - tags
    - release
    - hotfix
    - develop
    - /^feature-.*$/
    - /^bugfix-.*$/
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/*.deb
  tags:
    - docker
    - sci
    - ubuntu

# osx pipeline
ci:osx:
  stage: ci
  script:
    - source ./BuildServer/Unix/definitions_macos.sh
    - source ./BuildServer/Unix/version.sh
    - ./BuildServer/Unix/build.sh
    - ./BuildServer/Unix/tests.sh
  allow_failure: false
  only:
    - triggers
    - tags
    - release
    - hotfix
    - develop
    - /^feature-.*$/
    - /^bugfix-.*$/
  artifacts:
    paths:
    - ./BuildServer/Unix/Build_macOS
    expire_in: 1 day
  tags:
    - macos10.13

deploy:osx:
  stage: deploy
  script:
    - source ./BuildServer/Unix/definitions_macos.sh
    - source ./BuildServer/Unix/version.sh
    - ./BuildServer/Unix/deploy_macos.sh
  dependencies:
    - ci:osx
  when: on_success
  artifacts:
    paths:
     - BuildServer/MDANSE*.dmg
  tags:
    - macos10.13

# windows 7 pipeline
# "call" is mandatory, see https://gitlab.com/gitlab-org/gitlab-runner/issues/1051
ci:windows:
  stage: ci
  script:
    - call .\\BuildServer\\Windows\\definitions.bat
    - call .\\BuildServer\\Windows\\version.bat
    - call .\\BuildServer\\Windows\\build.bat
    - call .\\BuildServer\\Windows\\tests.bat
  allow_failure: false
  only:
    - triggers
    - tags
    - develop
    - release
    - hotfix
    - /^feature-.*$/
    - /^bugfix-.*$/
  artifacts:
    paths:
    - .\\BuildServer\\Windows\\Build
    expire_in: 1 day
  tags:
    - windows10

deploy:windows:
  stage: deploy
  script:
    - call .\\BuildServer\\Windows\\definitions.bat
    - call .\\BuildServer\\Windows\\version.bat
    - call .\\BuildServer\\Windows\\deploy.bat
  dependencies:
    - ci:windows
  when: on_success
  artifacts:
    paths:
     - BuildServer\\MDANSE*.exe
  tags:
    - windows10

