stages:
  - build

osx:
  stage: build
  script:
    - cd ./BuildServer/Darwin/Scripts
    - ./package.sh
  tags:
    - mac
  only:
    - tags
  allow_failure: false
  artifacts:
    paths:
    - BuildServer/Darwin/Build/*.dmg

windows:
  stage: build
  script:
    - c:\cygwin64\bin\bash -c "dos2unix.exe ./BuildServer/Windows/package.sh"
    - c:\cygwin64\bin\bash .\BuildServer\Windows\package.sh setup
    - c:\cygwin64\bin\bash .\BuildServer\Windows\package.sh build
  artifacts:
    paths:
    - BuildServer/Windows/Build/*.exe
  only:
    - tags
  tags:
    - windows
  allow_failure: false

linux:
   stage: build
   script:
     - ./BuildServer/Debian/build_deb.sh amd64 trusty
   artifacts:
     paths:
     - BuildServer/Debian/Build/*.deb
   only:
     - tags
   tags:
     - ubuntu14.04
   allow_failure: false
