
 version: 2
 build:
   os: ubuntu-22.04
   tools:
     python: "3.10"
     # You can also specify other tool versions:
     # nodejs: "16"

 # Build documentation in the docs/ directory with Sphinx
 sphinx:
    configuration: Doc/conf.py

 # Dependencies required to build your docs
 python:
    install:
    - requirements: Doc/requirements.txt
