line-length = 88
indent-width = 4
target-version = "py39"

extend-exclude = [
    "MDANSE/Src/MDANSE/Framework/Jobs/RigidBodyTrajectory.py",
    "MDANSE/Src/MDANSE/MolecularDynamics/Trajectory.py",
    "MDANSE/Tests",
    "MDANSE_GUI/Tests",
    "Doc",
    "MDANSE/Doc",
]

[lint]
select = [
    "PL",  # Pylint errors
    "E",   # Pycodestyle
    "W",   # Pycodestyle warnings
    "F",   # Pyflakes
    # "B",   # Flake8 bugbear
    # "SIM", # Flake8 Simplify
    # "A",   # Flake8 builtins
    # "COM", # Flake8 commas
    # "ISC", # Flake8 implicit string concat
    # "RSE", # Flake8 raise
    # "FA",  # Flake8 future
    # "FBT", # Flake8 boolean trap
    # "C4",  # Flake8 comprehensions
    # "Q",   # Flake8 Quotes
    # "RET", # Flake8 return
    # "ARG", # Flake8 unused args
    # "PTH", # Flake8 use pathlib
    "I",   # Isort
    # "RUF", # Ruff specific
    # "FURB",# Refurb
    # "PERF",# Perflint
    # "D",   # Pydocstyle
    "UP",  # Pyupgrade
    "T20",   # Print
]
ignore = [
    "E501",     # Line too long
    "F401",     # Unused import in init
    "E402",     # Import not at top
    "PLR2004",  # Magic number in comparison
    "PLR0912",  # Too many branches
    "PLR0913",  # Too many arguments
    "PLR0915",  # Too many statements
    "PLC0415",  # Top-level imports
]

[lint.isort]
known-first-party = ["MDANSE", "MDANSE_GUI"]
