FROM ci_mdanse_xenial

SHELL ["/bin/bash", "-c"]

ARG MDANSE_GIT_COMMIT

RUN GIT_SSL_NO_VERIFY=true git clone https://code.ill.fr/scientific-software/mdanse.git

WORKDIR mdanse

RUN git checkout ${MDANSE_GIT_COMMIT}

RUN source ./BuildServer/Unix/definitions_debian.sh ; source ./BuildServer/Unix/version.sh ; ./BuildServer/Unix/deploy_debian.sh

