["Generic neutron instrument"]
_name = "Generic neutron instrument"
_sample = "isotropic"
_technique = "QENS"
_resolution_type = "Gaussian"
_resolution_fwhm = "0.1"
_resolution_unit = "meV"
_qvector_type = "SphericalQVectors"
_q_unit = "1/ang"
_q_min = "0.1"
_q_max = "4.0"
_q_step = "0.1"
_q_width = "0.1"
_vectors_per_shell = "100"
_axis_1 = "1.0,0.0,0.0"
_axis_2 = "0.0,1.0,0.0"

["OSIRIS PG002"]
_name = "OSIRIS PG002"
_sample = "isotropic"
_technique = "QENS"
_resolution_type = "Gaussian"
_resolution_fwhm = "0.0254"
_resolution_unit = "meV"
_qvector_type = "SphericalQVectors"
_q_unit = "1/ang"
_q_min = "0.18"
_q_max = "1.8"
_q_step = "0.05"
_q_width = "0.02"
_vectors_per_shell = "60"
_axis_1 = "1.0,0.0,0.0"
_axis_2 = "0.0,1.0,0.0"

["OSIRIS PG004"]
_name = "OSIRIS PG004"
_sample = "isotropic"
_technique = "QENS"
_resolution_type = "Gaussian"
_resolution_fwhm = "0.099"
_resolution_unit = "meV"
_qvector_type = "SphericalQVectors"
_q_unit = "1/ang"
_q_min = "0.37"
_q_max = "3.6"
_q_step = "0.05"
_q_width = "0.02"
_vectors_per_shell = "60"
_axis_1 = "1.0,0.0,0.0"
_axis_2 = "0.0,1.0,0.0"

["IRIS PG002"]
_name = "IRIS PG002"
_sample = "isotropic"
_technique = "QENS"
_resolution_type = "Gaussian"
_resolution_fwhm = "0.0175"
_resolution_unit = "meV"
_qvector_type = "SphericalQVectors"
_q_unit = "1/ang"
_q_min = "0.18"
_q_max = "1.8"
_q_step = "0.05"
_q_width = "0.02"
_vectors_per_shell = "60"
_axis_1 = "1.0,0.0,0.0"
_axis_2 = "0.0,1.0,0.0"

["IRIS PG004"]
_name = "IRIS PG004"
_sample = "isotropic"
_technique = "QENS"
_resolution_type = "Gaussian"
_resolution_fwhm = "0.0545"
_resolution_unit = "meV"
_qvector_type = "SphericalQVectors"
_q_unit = "1/ang"
_q_min = "0.37"
_q_max = "3.6"
_q_step = "0.05"
_q_width = "0.02"
_vectors_per_shell = "60"
_axis_1 = "1.0,0.0,0.0"
_axis_2 = "0.0,1.0,0.0"

["Ideal results (no resolution)"]
_name = "Ideal results (no resolution)"
_sample = "isotropic"
_technique = "QENS"
_resolution_type = "ideal"
_resolution_fwhm = "0"
_resolution_unit = "meV"
_qvector_type = "SphericalQVectors"
_q_unit = "1/ang"
_q_min = "0.1"
_q_max = "10.0"
_q_step = "0.1"
_q_width = "0.01"
_vectors_per_shell = "50"
_axis_1 = "1.0,0.0,0.0"
_axis_2 = "0.0,1.0,0.0"
