FROM ubuntu:trusty

RUN apt-get update

RUN apt-get install -y tzdata

RUN apt-get upgrade -y

RUN apt-get install -y --no-install-recommends fakeroot
RUN apt-get install -y --no-install-recommends git
RUN apt-get install -y --no-install-recommends graphviz
RUN apt-get install -y --no-install-recommends dos2unix
RUN apt-get install -y --no-install-recommends texlive-full
RUN apt-get install -y --no-install-recommends texlive-latex-extra
RUN apt-get install -y --no-install-recommends libnetcdf-dev
RUN apt-get install -y --no-install-recommends g++
RUN apt-get install -y --no-install-recommends cython
RUN apt-get install -y --no-install-recommends python-dev

RUN apt-get install -y --no-install-recommends python-wxmpl
RUN apt-get install -y --no-install-recommends python-vtk
RUN apt-get install -y --no-install-recommends python-nose
RUN apt-get install -y --no-install-recommends python-sphinx
RUN apt-get install -y --no-install-recommends pyro

RUN apt-get install -y --no-install-recommends lsb-release

