#!/bin/bash

sed -i "$ a export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH" ~/.bashrc
sed -i "$ a export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH" ~/.profile
echo "export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH" > /etc/profile.d/mdanse.sh