FROM ci_mdanse_xenial

SHELL ["/bin/bash", "-c"]

ARG MDANSE_GIT_BRANCH_NAME

VOLUME builds

RUN source ./BuildServer/Unix/definitions_debian.sh ${MDANSE_GIT_BRANCH_NAME}; source ./BuildServer/Unix/version.sh ; ./BuildServer/Unix/deploy_debian.sh


