#    This file is part of MDANSE.
#
#    MDANSE is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
from __future__ import annotations

from collections import Counter
from collections.abc import Callable
from inspect import getfullargspec
from operator import itemgetter
from typing import TYPE_CHECKING, Any

import numpy as np

from MDANSE.Framework.AtomGrouping.grouping import pair_labels

if TYPE_CHECKING:
    import numpy.typing as npt

    from MDANSE.Framework.OutputVariables.IOutputVariable import OutputData
    from MDANSE.MolecularDynamics.Trajectory import Trajectory


def mdtraj_initial_params(
    mdtraj_analysis: Callable,
) -> tuple[list[str], list[tuple[str, Any]]]:
    """Return input arguments accepted by a function.

    Designed to find all the keyword arguments of an MDTraj analysis run
    and their default values.

    Parameters
    ----------
    mdtraj_analysis : Callable
        A function run on an MDTraj trajectory.

    Returns
    -------
    tuple[list[str], list[tuple[str, Any]]]
        List of arguments and dictionary of keyword arguments with default values.
    """
    full_arg_spec = getfullargspec(mdtraj_analysis)
    param_names = full_arg_spec.args
    default_vals = list(full_arg_spec.defaults)
    pars_with_vals = []
    while default_vals:
        pars_with_vals.append((param_names.pop(), default_vals.pop()))
    return param_names, pars_with_vals[::-1]


def process_hydrogen_bonds(
    mdtraj_results,
    output_data: OutputData,
    mdanse_trajectory: Trajectory,
    frame_selection: tuple[int, int, int],
    **kwargs,
):
    """Write the analysis results into an MDANSE .mda file.

    This function summarises the hydrogen bond statistics generated by
    the MDTraj wernet_nilsson function.

    Parameters
    ----------
    mdtraj_results : Any
        Output of the MDTraj analysis function.
    output_data : OutputData
        MDANSE results object, normally used for writing .mda files.
    mdanse_trajectory : Trajectory
        The MDANSE trajectory instance used in the analysis.
    frame_selection : tuple[int, int, int]
        Frame selection given as (start, stop, step values).
    """
    time_axis = mdanse_trajectory.time()[
        frame_selection[0] : frame_selection[1] : frame_selection[2]
    ]
    time_unit = "ps"
    output_data.add(
        "hbond/axes/time",
        "LineOutputVariable",
        time_axis,
        units=time_unit,
    )
    output_data.add(
        "hbond/count/total",
        "LineOutputVariable",
        np.zeros_like(time_axis),
        axis="hbond/axes/time",
        main_result=True,
        units="counts",
    )
    valid_elements = mdanse_trajectory.non_dummy_elements - {"H", "H1", "H2", "H3"}
    valid_indices = {
        index
        for index in mdanse_trajectory.atom_indices
        if mdanse_trajectory.atom_types[index] in valid_elements
    }
    plabels = pair_labels(mdanse_trajectory)
    for _, labels in plabels:
        label1, label2 = sorted(labels)
        output_data.add(
            f"hbond/count/{label1}-{label2}",
            "LineOutputVariable",
            np.zeros_like(time_axis),
            axis="hbond/axes/time",
            units="counts",
            main_result=True,
            partial_result=True,
        )
    if len(mdtraj_results):
        for frame_index, hbonds in enumerate(mdtraj_results):
            valid_hbonds = [
                [ind1, ind2]
                for ind1, _, ind2 in hbonds
                if ind1 in valid_indices and ind2 in valid_indices
            ]
            element_hbonds = np.array(
                itemgetter(*np.array(valid_hbonds).flatten())(
                    mdanse_trajectory.atom_names
                )
            ).reshape((len(valid_hbonds), 2))
            type_pairs = np.sort(element_hbonds, axis=1)
            output_data["hbond/count/total"][frame_index] = len(type_pairs)
            pair_counter = Counter(tuple(line) for line in type_pairs)
            for (label1, label2), counts in pair_counter.items():
                output_data[f"hbond/count/{label1}-{label2}"][frame_index] = counts


MDTRAJ_POSTPROCESSING = {
    "Hydrogen Bonds: Wernet-Nilsson": process_hydrogen_bonds,
    # "Hydrogen Bonds: Baker-Hubbard": process_hydrogen_bonds,
}
