FROM ci_mdanse_bionic

SHELL ["/bin/bash", "-c"]

ARG CI_COMMIT_SHORT_SHA
ARG CI_COMMIT_REF_NAME

ENV CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA
ENV CI_COMMIT_REF_NAME=$GITHUB_REF

COPY ./ /app/
WORKDIR /app

CMD source ./BuildServer/Unix/Debian/definitions.sh;  source ./BuildServer/Unix/setup_ci.sh; ./BuildServer/Unix/build.sh; ./BuildServer/Unix/tests.sh; cp -a $GITHUB_WORKSPACE/build /artifacts/; cp -a $GITHUB_WORKSPACE/temp /artifacts/