FROM ci_mdanse_bionic

SHELL ["/bin/bash", "-c"]

VOLUME builds

RUN source ./BuildServer/Unix/Debian/definitions.sh; source ./BuildServer/Unix/setup_ci.sh ; source ./BuildServer/Unix/bionic_dependencies_modification.sh ; ./BuildServer/Unix/Debian/deploy.sh


