#!/usr/bin/env python

import optparse
import sys

from nMOLDYN.Core.Error import Error
from nMOLDYN.Utilities.CommandLine import IndentedHelpFormatterWithNL
from nMOLDYN.GUI.Application import MainApplication, PeriodicTableApplication, PlotterApplication

class CommandLineParserError(Error):
    pass


class CommandLineParser(optparse.OptionParser):
    '''A sublcass of OptionParser.    
    '''

    def start(self):
        '''Starts the nmoldyn plotter directly from the command line.
        
        @param option: the option that triggered the callback.
        @type option: str
        
        @param opt_str: the option string seen on the command line.
        @type opt_str: str
    
        @param value: the argument for the option.
        @type value: str
    
        @param parser: the nMOLDYN option parser.
        @type parser: instance of nMOLDYNOptionParser
        '''
        
        app = MainApplication(None)
        app.MainLoop()
        
        self.exit()


    def start_periodictable(self):
        '''Starts the nmoldyn database directly from the command line.
        
        @param option: the option that triggered the callback.
        @type option: str
        
        @param opt_str: the option string seen on the command line.
        @type opt_str: str
    
        @param value: the argument for the option.
        @type value: str
    
        @param parser: the nMOLDYN option parser.
        @type parser: instance of nMOLDYNOptionParser
        '''
        
        app = PeriodicTableApplication()
        app.MainLoop()
        
        self.exit()

    
    def start_plotter(self):
        '''Starts the nmoldyn plotter directly from the command line.
        
        @param option: the option that triggered the callback.
        @type option: str
        
        @param opt_str: the option string seen on the command line.
        @type opt_str: str
    
        @param value: the argument for the option.
        @type value: str
    
        @param parser: the nMOLDYN option parser.
        @type parser: instance of nMOLDYNOptionParser
        '''
        
        app = PlotterApplication()
        app.MainLoop()
        
        self.exit()

if __name__ == "__main__":

    from nMOLDYN.__pkginfo__ import __version__, __versiondate__

    # Creates the option parser.
    parser = CommandLineParser(formatter=IndentedHelpFormatterWithNL(), version = 'nMolDyn %s (%s)' % (__version__, __versiondate__))        

    # Creates a first the group of general options.
    group = optparse.OptionGroup(parser, "General options")
    group.add_option("-d", "--database", action="store_true", dest="database", help='Start nMolDyn database application')
    group.add_option("-m", "--main", action="store_true", dest="main", help='Start nMolDyn main application')
    group.add_option("-p", "--plot", action="store_true", dest="plot", help='Start the nMolDyn plotting application')

    # Add the goup to the parser.
    parser.add_option_group(group)
        
    # The command line is parsed.        
    options, args = parser.parse_args()
    
    if options.main:
        parser.start()

    elif options.database:
        parser.start_periodictable()
    
    elif options.plot:
        parser.start_plotter()

    else:
        parser.start()
    
