#!python

import wx

from MDANSE.GUI.ElementsDatabaseEditor import ElementsDatabaseEditor

class ElementsDatabaseEditorApp(wx.App):
    
    def OnInit(self):
        
        f = ElementsDatabaseEditor(None)
        f.Show()
        self.SetTopWindow(f)
        return True

if __name__ == "__main__":
    
    app = ElementsDatabaseEditorApp(None)
    app.MainLoop()
    