#!python

import wx

from MDANSE.GUI.UserDefinitionViewer import UserDefinitionViewer

class UserDefinitionViewerApp(wx.App):  
      
    def OnInit(self):
        
        f = UserDefinitionViewer(None)
        f.Show()
        self.SetTopWindow(f)
        return True

if __name__ == "__main__":

    app = UserDefinitionViewerApp(None)
    app.MainLoop()
    