#!/usr/bin/env python

import wx

from MDANSE.GUI.MainFrame import MainFrame

class MainApplication(wx.App):
    
    def OnInit(self):
        
        f = MainFrame(None)
        f.Show()
        return True

if __name__ == "__main__":

    app = MainApplication(None)
    app.MainLoop()

    
