#!/usr/bin/env python

# **************************************************************************
#
# MDANSE: Molecular Dynamics Analysis for Neutron Scattering Experiments
#
# @file      Src/__init__.py
# @brief     Implements module/class/test __init__
#
# @homepage  https://mdanse.org
# @license   GNU General Public License v3 or higher (see LICENSE)
# @copyright Institut Laue Langevin 2013-now
# @copyright ISIS Neutron and Muon Source, STFC, UKRI 2021-now
# @authors   Scientific Computing Group at ILL (see AUTHORS)
#
# **************************************************************************

import argparse
import sys

def parse_args():

    parser = argparse.ArgumentParser(description='This is mdanse_job: a shortcut for running MDANSE job.')
    parser.add_argument('--trajectory','-t',dest='trajectory', required=False, help='MMTK Trajectory file')
    parser.add_argument('--job','-j',dest='job', required=True, help='Job to run')
    args = parser.parse_args()
    
    return args

if __name__ == "__main__":
    
    from MDANSE import REGISTRY
    from MDANSE.GUI.Apps import JobApp
    
    args = parse_args()
    trajectory = args.trajectory
    job = args.job

    if not REGISTRY['job'].has_key(job):
        print('Unknown job: %s' % job)
        sys.exit(1)

    for v in REGISTRY['job'][job].settings.values():
        if v[0] == 'mmtk_trajectory' and trajectory is None:
            print('A trajectory is needed')
            sys.exit(1)

    app = JobApp(job,trajectory)
    app.MainLoop()
    
