#!/usr/bin/env python

import optparse

from MDANSE.App.HelpFormatter import IndentedHelp
from MDANSE.App.Console.CommandLine import CommandLineParser

if __name__ == "__main__":

    from MDANSE.__pkginfo__ import __version__, __date__

    # Creates the option parser.
    parser = CommandLineParser(formatter=IndentedHelp(), version = 'MDANSE %s (%s)' % (__version__, __date__))        

    # Creates a first the group of general options.
    group = optparse.OptionGroup(parser, "General options")
    group.add_option('--add-mmtk-def', action='callback', callback=parser.add_mmtk_definition, help='Add a definition to the MMTK database.')
    group.add_option('-d', '--database', action='callback', callback=parser.display_element_info, help='Display chemical informations about a given element.')
    group.add_option('-r', '--registry', action='callback', callback=parser.query_classes_registry, help='Display the contents of MDANSE classes registry.')
    group.add_option('-t', '--traj', action='callback', callback=parser.display_trajectory_contents, help='Display the chemical contents of a trajectory.')

    # Add the goup to the parser.
    parser.add_option_group(group)
    
    # Creates a second group of job-specific options.
    group = optparse.OptionGroup(parser, "Job managing options")

    # Add the goup to the parser.
    parser.add_option_group(group)

    group.add_option('--jcheck', action='callback', callback=parser.check_job, help='Check the status of a given job.')
    group.add_option('--jlist', action='callback', callback=parser.display_jobs_list, help='Display the jobs list.')
    group.add_option('--jrun' , action='callback', callback=parser.run_job, help='Run MDANSE job(s).')
    group.add_option('--jsave', action='callback', callback=parser.save_job_template, help='Save a template for a job.', metavar = "MDANSE_SCRIPT")
    
    # The command line is parsed.        
    options, _ = parser.parse_args()
