#!/usr/bin/env python

import cPickle
import glob
import optparse
import os
import subprocess               
import sys

from MDANSE import ELEMENTS, PLATFORM, REGISTRY
from MDANSE.Core.Error import Error
from MDANSE.Framework.Jobs.JobStatus import JobState
from MDANSE.App.HelpFormatter import IndentedHelp

class CommandLineParserError(Error):
    pass

class CommandLineParser(optparse.OptionParser):
    '''A sublcass of OptionParser.
    
    Creates the MDANSE commad line parser.
    '''
    
    def add_mmtk_definition(self, option, opt_str, value, parser):
        
        if len(parser.rargs) != 3:
            raise CommandLineParserError("Invalid number of arguments for %r option" % opt_str)
        
        from MDANSE import MMTK_DEFINITIONS
        
        MMTK_DEFINITIONS.add(*parser.rargs)
        
        MMTK_DEFINITIONS.save()

    def check_job(self, option, opt_str, value, parser):
        '''Display the jobs list
            
        @param option: the option that triggered the callback.
        @type option: optparse.Option instance
        
        @param opt_str: the option string seen on the command line.
        @type opt_str: str
    
        @param value: the argument for the option.
        @type value: str
    
        @param parser: the MDANSE option parser.
        @type parser: instance of MDANSEOptionParser
        '''

        if len(parser.rargs) != 1:
            raise CommandLineParserError("Invalid number of arguments for %r option" % opt_str)
        
        basename = parser.rargs[0]
        
        filename = os.path.join(PLATFORM.temporary_files_directory(),basename)
        
        if not os.path.exists(filename):
            raise CommandLineParserError("Invalid job name")
            
        # Open the job temporary file
        try:
            f = open(filename, 'rb')
            info = cPickle.load(f)
            f.close()
            
        # If the file could not be opened/unpickled for whatever reason, try at the next checkpoint
        except:
            raise CommandLineParserError("The job %r could not be opened properly." % basename)

        # The job file could be opened and unpickled properly
        else:
            # Check that the unpickled object is a JobStatus object
            if not isinstance(info,JobState):
                raise CommandLineParserError("Invalid contents for job %r." % basename)
            
            print "Information about %s job:" % basename
            for k,v in info.iteritems():            
                print "%-20s [%s]" % (k,v)

    def display_element_info(self, option, opt_str, value, parser):        
    
        if len(parser.rargs) != 1:
            raise CommandLineParserError("Invalid number of arguments for %r option" % opt_str)
        
        element = parser.rargs[0]
                
        try:
            print ELEMENTS.info(element)
        except ValueError:
            raise CommandLineParserError("The entry %r is not registered in the database" % element)
        
    def display_jobs_list(self, option, opt_str, value, parser):
        '''Display the jobs list
            
        @param option: the option that triggered the callback.
        @type option: optparse.Option instance
        
        @param opt_str: the option string seen on the command line.
        @type opt_str: str
    
        @param value: the argument for the option.
        @type value: str
    
        @param parser: the MDANSE option parser.
        @type parser: instance of MDANSEOptionParser
        '''

        if len(parser.rargs) != 0:
            raise CommandLineParserError("Invalid number of arguments for %r option" % opt_str)

        jobs = [f for f in glob.glob(os.path.join(PLATFORM.temporary_files_directory(),'*'))]
                                               
        for j in jobs:

            # Open the job temporary file
            try:
                f = open(j, 'rb')
                info = cPickle.load(f)
                f.close()
                
            # If the file could not be opened/unpickled for whatever reason, try at the next checkpoint
            except:
                continue

            # The job file could be opened and unpickled properly
            else:
                # Check that the unpickled object is a JobStatus object
                if not isinstance(info,JobState):
                    continue
                
                print "%-20s [%s]" % (os.path.basename(j),info["state"])

    def display_trajectory_contents(self, option, opt_str, value, parser):
        '''Displays trajectory contents
            
        @param option: the option that triggered the callback.
        @type option: optparse.Option instance
        
        @param opt_str: the option string seen on the command line.
        @type opt_str: str
    
        @param value: the argument for the option.
        @type value: str
    
        @param parser: the MDANSE option parser.
        @type parser: instance of MDANSEOptionParser
        '''
                
        trajName = parser.rargs[0]
        inputTraj = REGISTRY["input_data"]["mmtk_trajectory"](trajName)
        print inputTraj.info()
       
       
    def error(self, msg):
        '''Called when an error occured in the command line.
        
        @param msg: the error message.
        @type msg: str
        '''
        
        self.print_help(sys.stderr)
        print "\n"
        self.exit(2, "Error: %s\n" % msg)
    

    def query_classes_registry(self, option, opt_str, value, parser):
        '''
        Callback that displays the list of the jobs available in MDANSE
        
        @param option: the Option instance calling the callback.
        
        @param opt_str: the option string seen on the command-line triggering the callback
        
        @param value: the argument to this option seen on the command-line.
        
        @param parser: the MDANSEOptionParser instance.
        '''
            
        if len(parser.rargs) == 0:
            print "Registered interfaces:"
            for interfaceName in REGISTRY.get_interfaces():
                print "\t- %s" % interfaceName
        elif len(parser.rargs) == 1:
            val = parser.rargs[0]                    
            print REGISTRY.info(val.lower())
        else:
            raise CommandLineParserError("Invalid number of arguments for %r option" % opt_str)
            


    def run_job(self, option, opt_str, value, parser):
        '''Run job file(s).
            
        @param option: the option that triggered the callback.
        @type option: optparse.Option instance
        
        @param opt_str: the option string seen on the command line.
        @type opt_str: str
    
        @param value: the argument for the option.
        @type value: str
    
        @param parser: the MDANSE option parser.
        @type parser: instance of MDANSEOptionParser
        '''

        if len(parser.rargs) != 1:
            raise CommandLineParserError("Invalid number of arguments for %r option" % opt_str)

        filename = parser.rargs[0]
        
        if not os.path.exists(filename):
            raise CommandLineParserError("The job file %r could not be executed" % filename)
            
        subprocess.Popen([sys.executable, filename])


    def save_job_template(self, option, opt_str, value, parser):
        '''
        Save job templates.
            
        @param option: the option that triggered the callback.
        @type option: optparse.Option instance
        
        @param opt_str: the option string seen on the command line.
        @type opt_str: str
    
        @param value: the argument for the option.
        @type value: str
    
        @param parser: the MDANSE option parser.
        @type parser: instance of MDANSEOptionParser
        '''

        if len(parser.rargs) != 1:
            raise CommandLineParserError("Invalid number of arguments for %r option" % opt_str)
        
        jobs = REGISTRY["job"]
        
        name = parser.rargs[0]
                    
        # A name for the template is built.
        filename = os.path.abspath('template_%s.py' % name.lower())
        # Try to save the template for the job.
        try:
            jobs[name].save_job(filename)    
        # Case where an error occured when writing the template.
        except IOError:
            raise CommandLineParserError("Could not write the job template as %r" % filename)
        # If the job class has no save_job method, thisis not a valid nMolDyn job.
        except KeyError:
            raise CommandLineParserError("The job %r is not a valid MDANSE job" % name)
        # Otherwise, print some information about the saved template.
        else:
            print "Saved template for job %r as %r" % (name, filename)

if __name__ == "__main__":

    from MDANSE.__pkginfo__ import __version__, __date__

    # Creates the option parser.
    parser = CommandLineParser(formatter=IndentedHelp(), version = 'MDANSE %s (%s)' % (__version__, __date__))        

    # Creates a first the group of general options.
    group = optparse.OptionGroup(parser, "General options")
    group.add_option('--add-mmtk-def', action='callback', callback=parser.add_mmtk_definition, help='Add a definition to the MMTK database.')
    group.add_option('-d', '--database', action='callback', callback=parser.display_element_info, help='Display chemical informations about a given element.')
    group.add_option('-r', '--registry', action='callback', callback=parser.query_classes_registry, help='Display the contents of nmoldyn classes registry.')
    group.add_option('-t', '--traj', action='callback', callback=parser.display_trajectory_contents, help='Display the chemical contents of a trajectory.')

    # Add the goup to the parser.
    parser.add_option_group(group)
    
    # Creates a second group of job-specific options.
    group = optparse.OptionGroup(parser, "Job managing options")

    # Add the goup to the parser.
    parser.add_option_group(group)

    group.add_option('--jcheck', action='callback', callback=parser.check_job, help='Check the status of a given job.')
    group.add_option('--jlist', action='callback', callback=parser.display_jobs_list, help='Display the jobs list.')
    group.add_option('--jrun' , action='callback', callback=parser.run_job, help='Run MDANSE job(s).')
    group.add_option('--jsave', action='callback', callback=parser.save_job_template, help='Save a template for a job.', metavar = "nMOLDYNSCRIPT")
    
    # The command line is parsed.        
    options, _ = parser.parse_args()
