FROM docker.ill.fr/scientific-software/mdanse:ubuntu-bionic

SHELL ["/bin/bash", "-c"]

ARG MDANSE_GIT_COMMIT

RUN GIT_SSL_NO_VERIFY=true git clone https://code.ill.fr/scientific-software/mdanse.git

WORKDIR mdanse

RUN git checkout ${MDANSE_GIT_COMMIT}

RUN source ./BuildServer/Unix/Debian/definitions.sh; source ./BuildServer/Unix/setup_ci.sh ; ./BuildServer/Unix/build.sh

RUN source ./BuildServer/Unix/Debian/definitions.sh; source ./BuildServer/Unix/setup_ci.sh ; ./BuildServer/Unix/tests.sh

