#    This file is part of MDANSE.
#
#    MDANSE is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
from __future__ import annotations

import struct
from collections.abc import Iterator
from itertools import islice
from os import SEEK_SET
from pathlib import Path
from typing import Literal

import numpy as np
from more_itertools import chunked, one

from MDANSE.Framework.Parsers.FortranUnformat import binary_file_reader
from MDANSE.Framework.Parsers.Parser import Parser
from MDANSE.Framework.Units import measure
from MDANSE.Mathematics.Geometry import get_basis_vectors_from_cell_parameters
from MDANSE.MolecularDynamics.UnitCell import UnitCell
from MDANSE.util_types import FloatArray

PI_2 = 0.5 * np.pi


class EndOfFile(Exception):
    pass


class ByteOrderError(Exception):
    pass


class DCDFileError(Exception):
    pass


class DCDFile(Parser):
    def __init__(self, filename: Path | str, **kwargs):
        super().__init__(filename)
        self._byte_order = self.get_byte_order(filename)

        dtype = np.dtype(np.float64)
        self._dtype = dtype.newbyteorder(self._byte_order)
        with self.filename.open("rb") as in_file:
            reader = binary_file_reader(in_file, self._byte_order)
            self.read_header(reader)

    @staticmethod
    def get_byte_order(filename: Path | str) -> Literal[">", "<"]:
        """Identity the byte order of the file by trial-and-error."""

        with open(filename, "rb") as in_file:
            data = in_file.read(4)

        # Check for low and big endianness byte orders.
        for order in ("<", ">"):
            if one(struct.unpack(order + "i", data)) == 84:
                return order

        raise ByteOrderError(f"Invalid byte order. {filename} not a valid DCD file")

    def read_header(self, reader) -> None:
        """Read a DCD file header.

        Notes
        -----
        c.f. https://www.ks.uiuc.edu/Research/vmd/plugins/molfile/dcdplugin.html
        """
        # Read a block
        data = next(reader)

        if data[:4] != b"CORD":
            raise DCDFileError("Unrecognized DCD format")

        data = data[4:]
        self.charmm = one(struct.unpack(self._byte_order + "i", data[-4:]))

        struc = "9if10i" if self.charmm else "9id9i"

        temp = struct.unpack(self._byte_order + struc, data)

        (
            self.n_frames,
            self.start_step,
            self.interval,
            _,  # Zeroes
            self.n_fixed,
            self.time_delta,
            self.has_pbc_data,
            self.has_4d,
        ) = temp[0], temp[1], temp[2], temp[3:8], temp[8], temp[9], temp[10], temp[11]

        # Stop if there are fixed atoms.
        if self.n_fixed:
            raise DCDFileError("Can not handle fixed atoms yet.")

        # The time step is in AKMA time
        self.time_step = (
            self.interval * self.time_delta * measure(1.0, "akma_time").toval("ps")
        )

        # Read a block
        data = next(reader)

        self.title = b"\n".join(
            chunk.strip() for chunk in map(bytes, chunked(data[4:], 80))
        )

        # Read a block
        data = next(reader)

        # Read the number of atoms.
        self._n_atoms = one(struct.unpack(self._byte_order + "i", data))

    def read_step(self, reader) -> tuple[UnitCell | None, FloatArray]:
        """
        Reads a frame of the DCD file.
        """

        if self.has_pbc_data:
            unit_cell = np.frombuffer(next(reader), dtype=self._dtype, count=6)
            unit_cell = unit_cell[[0, 2, 5, 1, 3, 4]]
            # The unit cell is converted from ang to nm
            unit_cell[0:3] *= measure(1.0, "ang").toval("nm")

            # This file was generated by CHARMM, or by NAMD > 2.5, with the angle
            # cosines of the periodic cell angles written to the DCD file.
            # This formulation improves rounding behavior for orthogonal cells
            # so that the angles end up at precisely 90 degrees, unlike acos().
            # See https://github.com/MDAnalysis/mdanalysis/wiki/FileFormats for info
            if np.all(abs(unit_cell[3:]) <= 1):
                unit_cell[3:] = PI_2 - np.arcsin(unit_cell[3:])
            else:
                # assume the angles are stored in degrees (NAMD <= 2.5)
                unit_cell[3:] = np.deg2rad(unit_cell[3:])

            unit_cell = get_basis_vectors_from_cell_parameters(unit_cell)
            unit_cell = UnitCell(unit_cell)

        else:
            unit_cell = None

        config = (
            np.frombuffer(
                b"".join(islice(reader, 3)),
                count=3 * self.n_atoms,
                dtype=np.float32,
            )
            .reshape(self.n_atoms, 3, order="F")
            .astype(np.float64)
        )
        config *= measure(1.0, "ang").toval("nm")

        if self.has_4d:
            reader.send(1)

        return unit_cell, config

    @property
    def n_atoms(self) -> int:
        return self._n_atoms

    @property
    def element_list(self) -> list[str]:
        return ["Unknown"] * self.n_atoms

    @property
    def frames(self) -> Iterator:
        with self.filename.open("rb") as inp:
            reader = binary_file_reader(inp, self._byte_order)
            self.read_header(reader)

            try:
                while True:
                    yield self.read_step(reader)
            except StopIteration:
                pass
