name: Black

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint-mdanse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "MDANSE/Src"

  lint-mdanse-gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "MDANSE_GUI/Src"
