name: CI/CD

on: [push, workflow_dispatch]

jobs:
  docker_pre_clean:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - run: $GITHUB_WORKSPACE/BuildServer/Docker/clean.sh
  
  ci_ubuntu:
    if: always()
    needs: docker_pre_clean
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install NetCDF
        run: sudo apt-get install netcdf-bin libnetcdf-dev
      - name: Set up docker
        run: docker build --force-rm=true -t ci_mdanse_bionic -f $GITHUB_WORKSPACE/BuildServer/Docker/Ubuntu-bionic/Dockerfile_setup .
      - name: Build MDANSE
        run: docker build --force-rm=true --build-arg CI_COMMIT_SHORT_SHA=${GITHUB_SHA::8} --build-arg CI_COMMIT_REF_NAME=$GITHUB_REF --no-cache -t ci_mdanse_bionic_build -f $GITHUB_WORKSPACE/BuildServer/Docker/Ubuntu-bionic/Dockerfile_build .
      - name: Generate artifacts
        run: docker run -iv$PWD:/artifacts/ ci_mdanse_bionic_build
      - name: 'Archive artifacts'
        uses: actions/upload-artifact@v2
        with:
          path: |
            $GITHUB_WORKSPACE/build
            $GITHUB_WORKSPACE/temp
          retention-days: 1/24

  deploy_ubuntu:
    runs-on: ubuntu-18.04
    needs: ci_ubuntu
    if: |
      contains( github.ref, 'master' ) ||
      contains( github.ref, 'develop' ) ||
      contains( github.ref, 'release-' ) ||
      contains( github.ref, 'hotfix-' ) ||
      contains( github.ref, 'build-' ) ||
      contains( github.ref, 'tags' ) ||
      contains( github.ref, 'web' ) ||
      contains( github.ref, '19_continuous_integration' )
    steps:
      - uses: actions/checkout@v2
      - name: Set up docker
        run: docker build --force-rm=true -t ci_mdanse_bionic -f $GITHUB_WORKSPACE/BuildServer/Docker/Ubuntu-bionic/Dockerfile_setup .
      - name: Deploy
        run: docker build --force-rm=true --build-arg CI_COMMIT_SHORT_SHA=${GITHUB_SHA::8} --build-arg CI_COMMIT_REF_NAME=$GITHUB_REF --no-cache -t ci_mdanse_bionic_build -f $GITHUB_WORKSPACE/BuildServer/Docker/Ubuntu-bionic/Dockerfile_deploy .
      - name: Generate artifacts
        run: docker run -iv${PWD}:/artifacts/ ci_mdanse_bionic_build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: $GITHUB_WORKSPACE/*.deb 
          retention-days: 1/24
  
  docker_post_clean:
    if: always()
    needs: deploy_ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - run: $GITHUB_WORKSPACE/BuildServer/Docker/clean.sh

  test_ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - name: Install libraries
        run: sudo apt-get install netcdf-bin libnetcdf-dev libwxgtk3.0-dev python-wxgtk3.0 libvtk6.3 libvtk6-dev python-vtk6 python-dev
      - name: Install python dependencies with pip
        run: |
          mkdir $HOME/temp_install
          cd $HOME
          python2 -m pip install virtualenv
          python2 -m virtualenv $HOME/mdanse_venv
          source $HOME/mdanse_venv/bin/activate
          pip install numpy==1.16.6 matplotlib==2.2.5 Cython==0.29.24 Pyro
      - name: Install ScientificPython
        run: |
          source $HOME/mdanse_venv/bin/activate
          git clone https://code.ill.fr/scientific-software/scientific-python.git
          cd scientific-python/
          python setup.py build
          sudo $HOME/mdanse_venv/bin/python setup.py install --prefix=$HOME/temp_install
      - run: dpkg -L libnetcdf-dev
      - name: Install MMTK
        run: |
          source $HOME/mdanse_venv/bin/activate
          cd ..
          git clone https://code.ill.fr/scientific-software/mmtk.git
          cd mmtk
          export NETCDF_HEADER_FILE_PATH=$NETCDF_HEADER_FILE_PATH:/usr/include/python2.7/
          sudo $HOME/mdanse_venv/bin/python setup.py install --prefix=$HOME/temp_install
        env:
          NETCDF_HEADER_FILE_PATH: /usr/include/
      - uses: actions/checkout@v2
      - name: Install MDANSE
        run: |
          source $HOME/mdanse_venv/bin/activate
          cd $GITHUB_WORKSPACE
          python setup.py install --prefix=$HOME/temp_install
      - name: Run tests
        run: |
          source $HOME/mdanse_venv/bin/activate
          source $GITHUB_WORKSPACE/BuildServer/Unix/MacOS/definitions.sh
          $GITHUB_WORKSPACE/BuildServer/Unix/tests.sh

  # OSX
  ci_osx:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install NetCDF
        run: |
          brew install netcdf
          export NETCDF_HEADER_FILE_PATH=/usr/include/:/usr/local/include/
      - name: Install dependecies
        run: |
          python2 -m pip install virtualenv
          python2 -m virtualenv $HOME/mdanse_venv
          source $HOME/mdanse_venv/bin/activate
          python2 -m pip install numpy==1.16.6 matplotlib==2.2.5 Cython==0.29.24
      - name: Prepare virtual machine
        run: |
          source $HOME/mdanse_venv/bin/activate
          source $GITHUB_WORKSPACE/BuildServer/Unix/MacOS/definitions.sh
          source $GITHUB_WORKSPACE/BuildServer/Unix/setup_ci.sh
      - run: $GITHUB_WORKSPACE/BuildServer/Unix/build.sh
      - name: Install ScientificPython
        run: |
          export NETCDF_HEADER_FILE_PATH=/usr/include/:/usr/local/include/:/usr/local/:/usr/local/lib:/usr/local/bin
          mkdir -p $GITHUB_WORKSPACE/temp/install
          source $HOME/mdanse_venv/bin/activate
          cd $HOME
          git clone https://code.ill.fr/scientific-software/scientific-python.git
          cd scientific-python
          sudo $HOME/mdanse_venv/bin/python setup.py install --prefix=$HOME/temp/install
      - name: Install MMTK
        run: |
          source $HOME/mdanse_venv/bin/activate
          cd $HOME
          git clone https://code.ill.fr/scientific-software/mmtk.git
          cd mmtk
          export NETCDF_HEADER_FILE_PATH=/usr/local/include/:/usr/local/:/usr/local/lib:/usr/local/bin
          echo $NETCDF_HEADER_FILE_PATH
          sudo $HOME/mdanse_venv/bin/python setup.py install --prefix=$HOME/temp_install
      - name: Install MDANSE
        run: |
          source $HOME/mdanse_venv/bin/activate
          cd $GITHUB_WORKSPACE
          python setup.py install --prefix=$HOME/temp_install
      - name: Run tests
        run: |
          source $HOME/mdanse_venv/bin/activate
          $GITHUB_WORKSPACE/BuildServer/Unix/tests.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OSX_artifacts
          path: |
            $GITHUB_WORKSPACE/build
            $GITHUB_WORKSPACE/temp
          retention-days: 1/24
  
  deploy_osx:
    needs: ci_osx
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: OSX_artifacts
      - name: Prepare virtual machine
        run: |
          source $GITHUB_WORKSPACE/BuildServer/Unix/MacOS/definitions.sh
          source $GITHUB_WORKSPACE/BuildServer/Unix/setup_ci.sh
      - name: Deploy
        run: $GITHUB_WORKSPACE/BuildServer/Unix/MacOS/deploy.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OSX_deploy_artifacts
          path: $GITHUB_WORKSPACE/*.dmg
    if: |
      contains( github.ref, 'master' ) ||
      contains( github.ref, 'develop' ) ||
      contains( github.ref, 'release-' ) ||
      contains( github.ref, 'hotfix-' ) ||
      contains( github.ref, 'build-' ) ||
      contains( github.ref, 'tags' ) ||
      contains( github.ref, 'web' )
  
  # WINDOWS
  test_windows:
    runs-on: windows-2019
    steps:
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7.18'
      - uses: actions/checkout@v2
      - name: Install VC 2008 redist
        run: choco install vcredist2008
        shell: cmd
      - name: Install VS2008
        run: |
          cd $env:HOME
          Invoke-WebRequest http://download.microsoft.com/download/8/1/d/81d3f35e-fa03-485b-953b-ff952e402520/VS2008ProEdition90dayTrialENUX1435622.iso -UseBasicParsing -Outfile $env:HOME\vs2008.iso
          Mount-DiskImage -ImagePath $env:HOME\vs2008.iso
          Start-Process E:\Setup\setup.exe -ArgumentList "/q /full /norestart"
      - name: Install dependencies
        run: |
          which python
          python -m pip install numpy==1.16.6 matplotlib==2.2.5 Cython==0.29.24 Pyro
          cd "%GITHUB_WORKSPACE%\BuildServer\Windows\Dependencies\"
          python -m pip install PyQt4‑4.11.4‑cp27‑cp27m‑win_amd64.whl VTK‑6.3.0‑cp27‑cp27m‑win_amd64.whl wxPython_common‑3.0.2.0‑py2‑none‑any.whl wxPython‑3.0.2.0‑cp27‑none‑win_amd64.whl
        shell: cmd
      - name: Prepare NetCDF
        run: |
          choco install 7zip
          mkdir $env:HOME\netcdf
          Invoke-WebRequest https://downloads.unidata.ucar.edu/netcdf-c/4.8.1/windows_installers/netCDF4.8.1-NC3-64.exe -UseBasicParsing -Outfile $env:HOME\netcdf\netCDF.exe
      - name: Extract NetCDF
        run: |
          cd "%HOME%\netcdf"
          "C:\Program Files\7-Zip\7z.exe" e netCDF.exe
        shell: cmd
      - name: Install ScientificPython
        run: |
          cd %HOME%
          git clone https://code.ill.fr/scientific-software/scientific-python.git
          cd scientific-python
          python setup.py build --netcdf_prefix="%HOME%\netcdf" --netcdf_dll="%HOME%\netcdf" install
        shell: cmd

  ci_windows:
    runs-on: windows-2019
    steps:
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '2.7.18'
      - uses: actions/checkout@v2
      - name: Install VC 2008 redist
        run: choco install vcredist2008
        shell: cmd
      - name: Install VS2008
        run: |
          cd $env:HOME
          Invoke-WebRequest http://download.microsoft.com/download/8/1/d/81d3f35e-fa03-485b-953b-ff952e402520/VS2008ProEdition90dayTrialENUX1435622.iso -UseBasicParsing -Outfile $env:HOME\vs2008.iso
          Mount-DiskImage -ImagePath $env:HOME\vs2008.iso
          Start-Process E:\Setup\setup.exe -ArgumentList "/q /full /norestart"
      - name: Install dependencies
        run: |
          which python
          python -m pip install numpy==1.16.6 matplotlib==2.2.5 Cython==0.29.24 Pyro
          cd "%GITHUB_WORKSPACE%\BuildServer\Windows\Dependencies\"
          python -m pip install PyQt4‑4.11.4‑cp27‑cp27m‑win_amd64.whl VTK‑6.3.0‑cp27‑cp27m‑win_amd64.whl wxPython_common‑3.0.2.0‑py2‑none‑any.whl wxPython‑3.0.2.0‑cp27‑none‑win_amd64.whl
        shell: cmd
      - name: Prepare NetCDF
        run: |
          choco install 7zip
          mkdir $env:HOME\netcdf
          Invoke-WebRequest https://downloads.unidata.ucar.edu/netcdf-c/4.8.1/windows_installers/netCDF4.8.1-NC3-64.exe -UseBasicParsing -Outfile $env:HOME\netcdf\netCDF.exe
      - name: Extract NetCDF
        run: |
          cd "%HOME%\netcdf"
          "C:\Program Files\7-Zip\7z.exe" e netCDF.exe
        shell: cmd
      - name: Set up virtual machine
        run: |
          call "%GITHUB_WORKSPACE%\\BuildServer\\Windows\\definitions.bat"
          call "%GITHUB_WORKSPACE%\\BuildServer\\Windows\\setup_ci.bat"
        shell: cmd
      - name: Build MDANSE
        run: |
          "%GITHUB_WORKSPACE%\\BuildServer\\Windows\\build.bat"
        shell: cmd
      - name: Run tests
        run: |
          call "%GITHUB_WORKSPACE%\\BuildServer\\Windows\\tests.bat"
        shell: cmd
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows_artifacts
          path: |
            "%GITHUB_WORKSPACE%\\BuildServer\\Windows\\Build"
            "%GITHUB_WORKSPACE%\\build"
            "%GITHUB_WORKSPACE%\\Extensions"
          retention-days: 1/24
  
  deploy_windows:
    needs: ci_windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Windows_artifacts
      - name: Set up virtual machine
        run: |
          call "%GITHUB_WORKSPACE%\\BuildServer\\Windows\\definitions.bat"
          call "%GITHUB_WORKSPACE%\\BuildServer\\Windows\\setup_ci.bat"
        shell: cmd
      - name: Deploy
        run: call "%GITHUB_WORKSPACE%\\BuildServer\\Windows\\deploy.bat"
        shell: cmd
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows_deploy_artifacts
          path: "%GITHUB_WORKSPACE%\\*.exe"
    if: |
      contains( github.ref, 'master' ) ||
      contains( github.ref, 'develop' ) ||
      contains( github.ref, 'release-' ) ||
      contains( github.ref, 'hotfix-' ) ||
      contains( github.ref, 'build-' ) ||
      contains( github.ref, 'tags' ) ||
      contains( github.ref, 'web' )
