name: Build MDANSE GUI

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]
        # os: [ubuntu-20.04, windows-2019, macOS-11, ubuntu-latest, windows-latest, macOS-latest]
    if: |
      contains( github.ref, 'protos' ) &&
      contains( github.ref, 'GUI' )
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
      
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.os }}_wheel
          path: ./MDANSE.whl

      - name: Install build packages
        run: python -m pip install build wheel setuptools

      - name: Install dependencies
        run: (cd MDANSE_GUI && python -m pip install -r requirements.txt)
      
      - name: Install MDANSE
        run: python -m pip install MDANSE.whl

      - name: Build wheels
        run: (cd MDANSE_GUI && python setup.py bdist_wheel)
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_GUI_wheel
          path: ./MDANSE_GUI/dist/*.whl
