name: Lint

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint-mdanse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./MDANSE/Src"
          args: "format --check"
          version: "0.13.0"

  lint_check_ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./MDANSE/Src"
          args: "check"
          version: "0.13.0"

  lint_format_ruff_gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./MDANSE_GUI/Src"
          args: "format --check"
          version: "0.13.0"

  lint_check_ruff_gui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: "./MDANSE_GUI/Src"
          args: "check"
          version: "0.13.0"

  lint_vermin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install vermin
        run: python -m pip install vermin

      - name: Run Vermin
        run: vermin -t=3.10 --lint --quiet --no-parse-comments MDANSE/ MDANSE_GUI/
