name: Lint

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

env:
  ruff_version: 0.15.2

jobs:

  lint:
    name: ${{ matrix.mdanse }} -- (${{ matrix.type }})
    strategy:
      fail-fast: false
      matrix:
        mdanse: ["MDANSE", "MDANSE_GUI"]
        type: ["check", "format --check"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: ./${{ matrix.mdanse }}/Src
          args: ${{ matrix.type }}
          version: ${{ env.ruff_version }}

  lint_copyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          args: check --preview --select CPY
          version: ${{ env.ruff_version }}

  lint_vermin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install vermin
        run: python -m pip install vermin

      - name: Run Vermin
        run: vermin -t=3.10 --lint --quiet --no-parse-comments MDANSE/ MDANSE_GUI/
