name: Test MDANSE

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Build MDANSE and run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        # os: [ubuntu-20.04, windows-2019, macOS-11, ubuntu-latest, windows-latest, macOS-latest]
    if: |
      !contains( github.ref, 'legacy' )
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pytest
        run: python -m pip install pytest

      - name: install MDANSE
        run: (cd MDANSE && python -m pip install .)

      - name: run unit tests
        run: |
          cd MDANSE/Tests/UnitTests
          python -m pytest
