name: Build MDANSE

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]
        # os: [ubuntu-20.04, windows-2019, macOS-11, ubuntu-latest, windows-latest, macOS-latest]
    if: |
      contains( github.ref, 'protos' )
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3

      - name: Install build packages
        run: python -m pip install build wheel setuptools

      - name: Install dependencies
        run: (cd MDANSE && python -m pip install -r requirements.txt)

      - name: Build wheels
        run: (cd MDANSE && python setup.py bdist_wheel)
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_wheel
          path: ./MDANSE/dist/*.whl

  build_gui_wheels:
    name: Build GUI wheels on ${{ matrix.os }}
    needs: [build_wheels]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]
        # os: [ubuntu-20.04, windows-2019, macOS-11, ubuntu-latest, windows-latest, macOS-latest]
    if: |
      contains( github.ref, 'protos' ) &&
      contains( github.ref, 'GUI' )
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
      
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.os }}_wheel

      - name: Install build packages
        run: python -m pip install build wheel setuptools

      - name: Install MDANSE
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: python -m pip install *.whl

      - name: Install MDANSE on Windows
        if: runner.os == 'Windows'
        run: FOR %i in (*.whl) DO python -m pip install %i

      - name: Install dependencies
        run: (cd MDANSE_GUI && python -m pip install -r requirements.txt)

      - name: Build wheels
        run: (cd MDANSE_GUI && python setup.py bdist_wheel)
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}_GUI_wheel
          path: ./MDANSE_GUI/dist/*.whl

